import 'package:studio_25_pilates_app/domain/entities/pilates_class.dart';

final List<PilatesClass> listClass = [
  PilatesClass(
    id: '1',
    nombre: 'Enrollamiento de espalda',
    fechaHora: DateTime(2025, 08, 19, 17, 30),
    duracion: Duration(minutes: 30),
    instructor: 'Raul Jimenez',
    cupoMaximo: 10,
    nivel: 'Principiante',
    cuposOcupados: 4,
  ),
  PilatesClass(
    id: '2',
    nombre: 'Pilates de suelo',
    fechaHora: DateTime(2025, 08, 19, 9, 0),
    duracion: Duration(minutes: 45),
    instructor: 'Laura Torres',
    cupoMaximo: 12,
    nivel: 'Intermedio',
    cuposOcupados: 9,
  ),
  PilatesClass(
    id: '3',
    nombre: 'Fortalecimiento de core',
    fechaHora: DateTime(2025, 08, 21, 18, 30),
    duracion: Duration(minutes: 60),
    instructor: 'Andrés López',
    cupoMaximo: 8,
    nivel: 'Avanzado',
    cuposOcupados: 6,
  ),
  PilatesClass(
    id: '4',
    nombre: 'Estiramiento y movilidad',
    fechaHora: DateTime(2025, 08, 22, 7, 0),
    duracion: Duration(minutes: 40),
    instructor: 'Mariana Pérez',
    cupoMaximo: 15,
    nivel: 'Principiante',
    cuposOcupados: 10,
  ),
  PilatesClass(
    id: '5',
    nombre: 'Pilates con bandas elásticas',
    fechaHora: DateTime(2025, 08, 22, 19, 0),
    duracion: Duration(minutes: 50),
    instructor: 'Carlos Gómez',
    cupoMaximo: 10,
    nivel: 'Intermedio',
    cuposOcupados: 2,
  ),
  PilatesClass(
    id: '6',
    nombre: 'Pilates de fuerza y equilibrio',
    fechaHora: DateTime(2025, 08, 23, 8, 30),
    duracion: Duration(minutes: 55),
    instructor: 'Raul Jimenez',
    cupoMaximo: 12,
    nivel: 'Avanzado',
    cuposOcupados: 10,
  ),
  PilatesClass(
    id: '7',
    nombre: 'Pilates para postura',
    fechaHora: DateTime(2025, 08, 23, 17, 0),
    duracion: Duration(minutes: 35),
    instructor: 'Laura Torres',
    cupoMaximo: 10,
    nivel: 'Principiante',
    cuposOcupados: 4,
  ),
  PilatesClass(
    id: '8',
    nombre: 'Pilates para flexibilidad',
    fechaHora: DateTime(2025, 08, 24, 7, 30),
    duracion: Duration(minutes: 40),
    instructor: 'Mariana Pérez',
    cupoMaximo: 14,
    nivel: 'Principiante',
    cuposOcupados: 7,
  ),
  PilatesClass(
    id: '9',
    nombre: 'Pilates con fitball',
    fechaHora: DateTime(2025, 08, 24, 18, 0),
    duracion: Duration(minutes: 50),
    instructor: 'Carlos Gómez',
    cupoMaximo: 12,
    nivel: 'Intermedio',
    cuposOcupados: 5,
  ),
  PilatesClass(
    id: '10',
    nombre: 'Pilates de respiración y control',
    fechaHora: DateTime(2025, 08, 25, 9, 30),
    duracion: Duration(minutes: 45),
    instructor: 'Laura Torres',
    cupoMaximo: 10,
    nivel: 'Principiante',
    cuposOcupados: 3,
  ),
  PilatesClass(
    id: '11',
    nombre: 'Pilates dinámico',
    fechaHora: DateTime(2025, 08, 25, 19, 0),
    duracion: Duration(minutes: 60),
    instructor: 'Andrés López',
    cupoMaximo: 15,
    nivel: 'Avanzado',
    cuposOcupados: 12,
  ),
  PilatesClass(
    id: '12',
    nombre: 'Pilates para columna',
    fechaHora: DateTime(2025, 08, 26, 8, 0),
    duracion: Duration(minutes: 35),
    instructor: 'Raul Jimenez',
    cupoMaximo: 10,
    nivel: 'Intermedio',
    cuposOcupados: 6,
  ),
  PilatesClass(
    id: '13',
    nombre: 'Pilates de fuerza integral',
    fechaHora: DateTime(2025, 08, 26, 18, 30),
    duracion: Duration(minutes: 55),
    instructor: 'Carlos Gómez',
    cupoMaximo: 12,
    nivel: 'Avanzado',
    cuposOcupados: 8,
  ),
  PilatesClass(
    id: '14',
    nombre: 'Pilates suave (bajo impacto)',
    fechaHora: DateTime(2025, 08, 27, 7, 0),
    duracion: Duration(minutes: 30),
    instructor: 'Mariana Pérez',
    cupoMaximo: 15,
    nivel: 'Principiante',
    cuposOcupados: 9,
  ),
  PilatesClass(
    id: '15',
    nombre: 'Pilates de tonificación',
    fechaHora: DateTime(2025, 08, 27, 19, 30),
    duracion: Duration(minutes: 50),
    instructor: 'Laura Torres',
    cupoMaximo: 10,
    nivel: 'Intermedio',
    cuposOcupados: 7,
  ),
  PilatesClass(
    id: '16',
    nombre: 'Aero Rumba',
    fechaHora: DateTime(2025, 08, 27, 19, 30),
    duracion: Duration(minutes: 50),
    instructor: 'Ronald Vera',
    cupoMaximo: 10,
    nivel: 'Intermedio',
    cuposOcupados: 7,
  ),
];
