// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT8F3relHcNg-rgINvfWmqqZJ7_r61F1U',
    appId: '1:927584476682:web:1973633c5a3f3f485849f3',
    messagingSenderId: '927584476682',
    projectId: 'mops-97de9',
    authDomain: 'mops-97de9.firebaseapp.com',
    storageBucket: 'mops-97de9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp_0bHlY60NVZBwhO8rwru4kOR__01lEE',
    appId: '1:927584476682:android:4f6f46c23ecd9be15849f3',
    messagingSenderId: '927584476682',
    projectId: 'mops-97de9',
    storageBucket: 'mops-97de9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvZhByWdKfD_pk8Ebps25LMkJDFFg1b4k',
    appId: '1:927584476682:ios:657821485a24760e5849f3',
    messagingSenderId: '927584476682',
    projectId: 'mops-97de9',
    storageBucket: 'mops-97de9.firebasestorage.app',
    iosBundleId: 'co.bitsolar.pilates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvZhByWdKfD_pk8Ebps25LMkJDFFg1b4k',
    appId: '1:927584476682:ios:657821485a24760e5849f3',
    messagingSenderId: '927584476682',
    projectId: 'mops-97de9',
    storageBucket: 'mops-97de9.firebasestorage.app',
    iosBundleId: 'co.bitsolar.pilates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT8F3relHcNg-rgINvfWmqqZJ7_r61F1U',
    appId: '1:927584476682:web:ff42d9044d0e1c425849f3',
    messagingSenderId: '927584476682',
    projectId: 'mops-97de9',
    authDomain: 'mops-97de9.firebaseapp.com',
    storageBucket: 'mops-97de9.firebasestorage.app',
  );
}
